# Configuration for https://pre-commit.ci
repos:
  # Update hooks weekly
  - repo: https://github.com/pre-commit/pre-commit-hooks
    autoupdate_schedule: weekly
  - repo: https://github.com/astral-sh/ruff-pre-commit
    autoupdate_schedule: weekly
  - repo: https://github.com/pre-commit/mirrors-mypy
    autoupdate_schedule: weekly
  - repo: https://github.com/gitleaks/gitleaks
    autoupdate_schedule: weekly

# Skip certain hooks on pre-commit.ci if needed
ci:
  skip: [mypy] # Skip mypy if it causes issues in CI
